rule all:
    input:
        "../results/lfqbench/plot/SampleComposition.pdf"

rule copy:
    input:
        "../results/tric/feature_alignment.tsv"
    output:
        "../results/lfqbench/OpenSWATH.tsv"
    shell:
        "ln {input} {output}"

rule lfqbench:
    input:
        rules.copy.output
    output:
        "../results/lfqbench/plot/SampleComposition.pdf"
    script:
        "scripts/lfqbench.R"

